runtime: nodejs10

instance_class: F2

env_variables:
  HOST: 'cluster0-ebvoq.gcp.mongodb.net'
  NODE_ENV: 'production'
  DATABASE_NAME: 'cms-strapi'
  DATABASE_USERNAME: 'admin'
  DATABASE_PASSWORD: 'os1967isFun'

